---
- hosts: nxos
  gather_facts: false
  tasks:
    - name: Manage NXOS features
      cisco.nxos.nxos_feature:
        feature: "{{ item.name }}"
        state: "{{ item.state|default('enabled') }}"
      loop: "{{ nxos_features }}"
